env:
  global:
    - CC_TEST_REPORTER_ID=a91e90b096ca9224bd1fdfd1b099b8c7d699722ac9b3530bfbb570b2b8c573f9

language: ruby
rvm:
- 2.4.4

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
deploy:
  run: "rails db:migrate"
  provider: heroku
  api_key: 79915276-7167-455d-a257-8cfd69afafeb
  app: lpa2-pizza-project
  on:
    repo: ajarno/lpa2-pizza-project
